-- Migration V11: One-time password reset tokens for forgot-password flow.
-- Only the SHA-256 of the token is stored to prevent usable links from leaking in DB dumps.

CREATE TABLE user_password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT      NOT NULL REFERENCES tenant(id),
    user_id    BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token_hash TEXT        NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_password_reset_token_user ON user_password_reset_token(user_id);
CREATE INDEX idx_user_password_reset_token_lookup ON user_password_reset_token(token_hash) WHERE used_at IS NULL;

ALTER TABLE user_password_reset_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_password_reset_token FORCE  ROW LEVEL SECURITY;

CREATE POLICY user_password_reset_token_tenant_isolation ON user_password_reset_token
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON user_password_reset_token TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
