-- M3.3: online donations via each trust's own Razorpay account (ADR 0013).

-- The trust's gateway credentials. The secret is AES-256-GCM ciphertext (tenant-bound); the
-- key id is public (Checkout needs it).
CREATE TABLE payment_settings (
    tenant_id      BIGINT      PRIMARY KEY REFERENCES tenant(id),
    provider       TEXT        NOT NULL CHECK (provider = 'RAZORPAY'),
    key_id         TEXT        NOT NULL CHECK (key_id ~ '^rzp_(test|live)_[A-Za-z0-9]{8,32}$'),
    key_secret_enc TEXT        NOT NULL,
    updated_by     BIGINT      NOT NULL REFERENCES app_user(id),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A donor's attempt to pay: created with the server-side amount before Checkout opens.
CREATE TABLE payment_intent (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT      NOT NULL REFERENCES tenant(id),
    razorpay_order_id   TEXT        NOT NULL UNIQUE,
    amount_paise        BIGINT      NOT NULL CHECK (amount_paise BETWEEN 100 AND 100000000),
    donor_name          TEXT        NOT NULL CHECK (length(donor_name) BETWEEN 1 AND 120),
    purpose             TEXT        CHECK (length(purpose) <= 120),
    status              TEXT        NOT NULL CHECK (status IN ('CREATED', 'PAID')),
    razorpay_payment_id TEXT        UNIQUE,
    donation_id         BIGINT      UNIQUE REFERENCES donation(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at             TIMESTAMPTZ,
    CONSTRAINT payment_intent_paid_shape CHECK (
        (status = 'CREATED' AND razorpay_payment_id IS NULL AND donation_id IS NULL) OR
        (status = 'PAID' AND razorpay_payment_id IS NOT NULL AND donation_id IS NOT NULL))
);
CREATE INDEX idx_payment_intent_pending ON payment_intent(tenant_id, status, created_at);

-- Wallets (and other online methods Razorpay reports) as a payment mode.
ALTER TABLE donation DROP CONSTRAINT donation_mode_check;
ALTER TABLE donation ADD CONSTRAINT donation_mode_check
    CHECK (mode IN ('CASH', 'UPI', 'CHEQUE', 'BANK_TRANSFER', 'CARD', 'WALLET'));

-- Ledger attribution: STAFF entries name who recorded them; ONLINE entries carry the gateway
-- payment id instead. recorded_by stays strictly required for STAFF.
ALTER TABLE donation ADD COLUMN channel TEXT NOT NULL DEFAULT 'STAFF'
    CHECK (channel IN ('STAFF', 'ONLINE'));
ALTER TABLE donation ADD COLUMN payment_ref TEXT UNIQUE;
ALTER TABLE donation ALTER COLUMN recorded_by DROP NOT NULL;
ALTER TABLE donation ADD CONSTRAINT donation_attribution CHECK (
    (channel = 'STAFF' AND recorded_by IS NOT NULL AND payment_ref IS NULL) OR
    (channel = 'ONLINE' AND recorded_by IS NULL AND payment_ref IS NOT NULL));

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['payment_settings', 'payment_intent'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I '
            'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint) '
            'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint)',
            t || '_tenant_isolation', t);
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON payment_settings, payment_intent TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
