-- V12: Devotee Portal, Self-Service Registration, OTP Auth, and Online Donations.
-- Enables devotees to log in via Mobile OTP or Email OTP to <slug>.mandircenter.app
-- without requiring donor PAN.

-- 1. Relax staff-only audit constraints so self-service online actions have NULL staff recorded_by:
ALTER TABLE devotee ALTER COLUMN consent_recorded_by DROP NOT NULL;
ALTER TABLE devotee ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE devotee ALTER COLUMN updated_by DROP NOT NULL;
ALTER TABLE donation ALTER COLUMN recorded_by DROP NOT NULL;
ALTER TABLE receipt ALTER COLUMN issued_by DROP NOT NULL;

-- 2. Devotee Auth Tokens (6-digit OTPs and magic link tokens):
CREATE TABLE devotee_auth_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL REFERENCES tenant(id),
    target_type  TEXT        NOT NULL CHECK (target_type IN ('PHONE', 'EMAIL')),
    target_value TEXT        NOT NULL,
    token_hash   TEXT        NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    attempts     INT         NOT NULL DEFAULT 0,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_devotee_auth_token_lookup ON devotee_auth_token(tenant_id, target_type, target_value);

ALTER TABLE devotee_auth_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE devotee_auth_token FORCE  ROW LEVEL SECURITY;
CREATE POLICY devotee_auth_token_tenant_isolation ON devotee_auth_token
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 3. Devotee Sessions (MC_SESSION cookie tokens):
CREATE TABLE devotee_session (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT      NOT NULL REFERENCES tenant(id),
    devotee_id         BIGINT      NOT NULL REFERENCES devotee(id) ON DELETE CASCADE,
    session_token_hash TEXT        NOT NULL UNIQUE,
    expires_at         TIMESTAMPTZ NOT NULL,
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_devotee_session_lookup ON devotee_session(tenant_id, session_token_hash);

ALTER TABLE devotee_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE devotee_session FORCE  ROW LEVEL SECURITY;
CREATE POLICY devotee_session_tenant_isolation ON devotee_session
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 4. Role grants:
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON devotee_auth_token, devotee_session TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
