-- M4: events with free registration passes (ADR 0014). Paid passes come with M3.3's flow later.

CREATE TABLE event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT      NOT NULL REFERENCES tenant(id),
    title             TEXT        NOT NULL CHECK (length(title) BETWEEN 1 AND 120),
    description       TEXT        CHECK (length(description) <= 2000),
    starts_at         TIMESTAMPTZ NOT NULL,
    ends_at           TIMESTAMPTZ NOT NULL,
    capacity          INT         CHECK (capacity BETWEEN 1 AND 100000),      -- NULL = no limit
    status            TEXT        NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    registration_open BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by        BIGINT      NOT NULL REFERENCES app_user(id),
    updated_by        BIGINT      NOT NULL REFERENCES app_user(id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT event_time_order CHECK (ends_at > starts_at)
);
CREATE INDEX idx_event_tenant_starts ON event(tenant_id, status, starts_at);

-- A registration = one pass for 1-10 people. The pass code is a random bearer value (the
-- devotee shows it at the gate); unique per trust.
CREATE TABLE event_pass (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    event_id       BIGINT      NOT NULL REFERENCES event(id),
    pass_code      TEXT        NOT NULL CHECK (pass_code ~ '^[A-Z2-9]{10}$'),
    attendee_name  TEXT        NOT NULL CHECK (length(attendee_name) BETWEEN 1 AND 120),
    attendee_count INT         NOT NULL CHECK (attendee_count BETWEEN 1 AND 10),
    phone          TEXT        CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'),
    email          TEXT        CHECK (length(email) <= 254),
    status         TEXT        NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CANCELLED')),
    checked_in_at  TIMESTAMPTZ,
    checked_in_by  BIGINT      REFERENCES app_user(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT event_pass_code_unique UNIQUE (tenant_id, pass_code),
    CONSTRAINT event_pass_contact CHECK (phone IS NOT NULL OR email IS NOT NULL),
    CONSTRAINT event_pass_checkin_shape CHECK ((checked_in_at IS NULL) = (checked_in_by IS NULL))
);
CREATE INDEX idx_event_pass_event ON event_pass(event_id, status);

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['event', 'event_pass'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I '
            'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint) '
            'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint)',
            t || '_tenant_isolation', t);
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON event, event_pass TO sevacenter_app;  -- no DELETE: cancel instead
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
