-- V13: Mandir Center Services (Pujas & Sankalp, Utsav Darshan Passes, and Sevak Volunteer Signups).
-- Provides full Church Center-equivalent community engagement for Mandirs.

-- 1. Puja & Sankalp Bookings
CREATE TABLE puja_booking (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    devotee_id     BIGINT      REFERENCES devotee(id) ON DELETE SET NULL,
    booking_number TEXT        NOT NULL,
    puja_code      TEXT        NOT NULL,
    puja_name      TEXT        NOT NULL,
    puja_date      DATE        NOT NULL,
    time_slot      TEXT        NOT NULL,
    devotee_name   TEXT        NOT NULL,
    gotra          TEXT,
    nakshatra      TEXT,
    rashi          TEXT,
    family_members TEXT,
    contact        TEXT,
    amount_paise   BIGINT      NOT NULL DEFAULT 0,
    payment_mode   TEXT,
    status         TEXT        NOT NULL DEFAULT 'CONFIRMED',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_puja_booking_tenant_date ON puja_booking(tenant_id, puja_date);
CREATE INDEX idx_puja_booking_devotee ON puja_booking(tenant_id, devotee_id);

ALTER TABLE puja_booking ENABLE ROW LEVEL SECURITY;
ALTER TABLE puja_booking FORCE  ROW LEVEL SECURITY;
CREATE POLICY puja_booking_tenant_isolation ON puja_booking
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 2. Darshan E-Tokens & Utsav Passes
CREATE TABLE darshan_pass (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT      NOT NULL REFERENCES tenant(id),
    devotee_id           BIGINT      REFERENCES devotee(id) ON DELETE SET NULL,
    pass_number          TEXT        NOT NULL UNIQUE,
    event_code           TEXT        NOT NULL,
    event_name           TEXT        NOT NULL,
    visit_date           DATE        NOT NULL,
    time_slot            TEXT        NOT NULL,
    primary_devotee_name TEXT        NOT NULL,
    attendee_count       INT         NOT NULL DEFAULT 1,
    contact              TEXT        NOT NULL,
    status               TEXT        NOT NULL DEFAULT 'ACTIVE',
    checked_in_at        TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_darshan_pass_tenant_date ON darshan_pass(tenant_id, visit_date);
CREATE INDEX idx_darshan_pass_devotee ON darshan_pass(tenant_id, devotee_id);

ALTER TABLE darshan_pass ENABLE ROW LEVEL SECURITY;
ALTER TABLE darshan_pass FORCE  ROW LEVEL SECURITY;
CREATE POLICY darshan_pass_tenant_isolation ON darshan_pass
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 3. Sevak / Volunteer Registrations
CREATE TABLE sevak_signup (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES tenant(id),
    devotee_id       BIGINT      REFERENCES devotee(id) ON DELETE SET NULL,
    full_name        TEXT        NOT NULL,
    contact          TEXT        NOT NULL,
    seva_area        TEXT        NOT NULL,
    available_days   TEXT        NOT NULL,
    shift_preference TEXT        NOT NULL,
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sevak_signup_tenant ON sevak_signup(tenant_id);

ALTER TABLE sevak_signup ENABLE ROW LEVEL SECURITY;
ALTER TABLE sevak_signup FORCE  ROW LEVEL SECURITY;
CREATE POLICY sevak_signup_tenant_isolation ON sevak_signup
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 4. Role grants
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON puja_booking, darshan_pass, sevak_signup TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
