-- V14: Mandir Admin Management schema (Schedules, Puja Catalog, Events & Passes, Sevak assignments)
-- Enables temple staff/priests to configure and manage Mandir Center directly from SevaCenter.

-- 1. Mandir Schedule & Settings
CREATE TABLE mandir_setting (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT      NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    morning_hours        TEXT        NOT NULL DEFAULT '05:00 AM – 01:00 PM',
    evening_hours        TEXT        NOT NULL DEFAULT '04:00 PM – 09:30 PM',
    is_open_override     BOOLEAN     DEFAULT NULL,
    deity                TEXT        DEFAULT 'Pradhan Devata',
    address              TEXT        DEFAULT 'Temple Road, Central Sanctum',
    helpline             TEXT        DEFAULT '+91 98765 43210',
    panchang_tithi       TEXT        DEFAULT 'Shukla Paksha Ekadashi / Trayodashi',
    nakshatra            TEXT        DEFAULT 'Rohini / Uttara Phalguni',
    special_announcement TEXT        DEFAULT 'Special Darshan arrangements for upcoming festival. Senior citizens can use Priority Queue Pass.',
    aartis_json          TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT mandir_setting_tenant_unique UNIQUE (tenant_id)
);
CREATE INDEX idx_mandir_setting_tenant ON mandir_setting(tenant_id);

ALTER TABLE mandir_setting ENABLE ROW LEVEL SECURITY;
ALTER TABLE mandir_setting FORCE  ROW LEVEL SECURITY;
CREATE POLICY mandir_setting_tenant_isolation ON mandir_setting
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 2. Puja & Rituals Catalog
CREATE TABLE puja_catalog (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    code            TEXT        NOT NULL,
    name            TEXT        NOT NULL,
    deity           TEXT        NOT NULL,
    duration        TEXT        NOT NULL,
    dakshina_rupees BIGINT      NOT NULL,
    description     TEXT,
    prasad_included BOOLEAN     NOT NULL DEFAULT TRUE,
    active          BOOLEAN     NOT NULL DEFAULT TRUE,
    display_order   INT         NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT puja_catalog_tenant_code_unique UNIQUE (tenant_id, code)
);
CREATE INDEX idx_puja_catalog_tenant ON puja_catalog(tenant_id, active);

ALTER TABLE puja_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE puja_catalog FORCE  ROW LEVEL SECURITY;
CREATE POLICY puja_catalog_tenant_isolation ON puja_catalog
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 3. Mandir Utsavs & Events
CREATE TABLE mandir_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT      NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    code              TEXT        NOT NULL,
    name              TEXT        NOT NULL,
    event_date        DATE        NOT NULL,
    time_range        TEXT        NOT NULL,
    description       TEXT,
    highlights        TEXT,
    registration_open BOOLEAN     NOT NULL DEFAULT TRUE,
    max_capacity      INT         DEFAULT 500,
    active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT mandir_event_tenant_code_unique UNIQUE (tenant_id, code)
);
CREATE INDEX idx_mandir_event_tenant ON mandir_event(tenant_id, active);

ALTER TABLE mandir_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE mandir_event FORCE  ROW LEVEL SECURITY;
CREATE POLICY mandir_event_tenant_isolation ON mandir_event
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- 4. Extend existing tables for staff management
ALTER TABLE darshan_pass ADD COLUMN IF NOT EXISTS checked_in BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sevak_signup ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE sevak_signup ADD COLUMN IF NOT EXISTS assigned_team TEXT;
ALTER TABLE sevak_signup ADD COLUMN IF NOT EXISTS assigned_event TEXT;

ALTER TABLE puja_booking ADD COLUMN IF NOT EXISTS performed_by TEXT;
ALTER TABLE puja_booking ADD COLUMN IF NOT EXISTS performed_at TIMESTAMPTZ;

-- 5. Role grants
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON mandir_setting, puja_catalog, mandir_event TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
