-- MVP (MandirCenter operations): sevak / volunteer signups (ADR 0015).

CREATE TABLE sevak_signup (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL REFERENCES tenant(id),
    full_name    TEXT        NOT NULL CHECK (length(full_name) BETWEEN 1 AND 120),
    phone        TEXT        CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'),
    email        TEXT        CHECK (length(email) <= 254),
    seva_areas   TEXT        NOT NULL CHECK (length(seva_areas) BETWEEN 1 AND 300),
    availability TEXT        CHECK (length(availability) <= 300),
    notes        TEXT        CHECK (length(notes) <= 1000),
    status       TEXT        NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW', 'APPROVED', 'DECLINED')),
    reviewed_by  BIGINT      REFERENCES app_user(id),
    reviewed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT sevak_signup_contact CHECK (phone IS NOT NULL OR email IS NOT NULL),
    CONSTRAINT sevak_signup_review_shape CHECK ((status = 'NEW') = (reviewed_by IS NULL))
);
CREATE INDEX idx_sevak_signup_tenant ON sevak_signup(tenant_id, status, created_at);

ALTER TABLE sevak_signup ENABLE ROW LEVEL SECURITY;
ALTER TABLE sevak_signup FORCE  ROW LEVEL SECURITY;
CREATE POLICY sevak_signup_tenant_isolation ON sevak_signup
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON sevak_signup TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
