-- MVP (MandirCenter operations): puja / sankalp bookings (ADR 0016). A puja's dakshina is a fee
-- for a service: seva income, NOT an 80G-eligible donation, so it never enters the donation ledger.

CREATE TABLE puja (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    name           TEXT        NOT NULL CHECK (length(name) BETWEEN 1 AND 120),
    deity          TEXT        CHECK (length(deity) <= 120),
    description    TEXT        CHECK (length(description) <= 1000),
    dakshina_paise BIGINT      NOT NULL CHECK (dakshina_paise BETWEEN 0 AND 10000000),   -- 0 = free
    active         BOOLEAN     NOT NULL DEFAULT TRUE,
    display_order  INT         NOT NULL DEFAULT 0,
    updated_by     BIGINT      NOT NULL REFERENCES app_user(id),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_puja_tenant ON puja(tenant_id, active, display_order);

CREATE TABLE puja_booking (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    puja_id        BIGINT      NOT NULL REFERENCES puja(id),
    booking_code   TEXT        NOT NULL CHECK (booking_code ~ '^[A-Z2-9]{10}$'),
    puja_name      TEXT        NOT NULL,                     -- snapshot
    devotee_name   TEXT        NOT NULL CHECK (length(devotee_name) BETWEEN 1 AND 120),
    gotra          TEXT        CHECK (length(gotra) <= 60),
    nakshatra      TEXT        CHECK (length(nakshatra) <= 60),
    rashi          TEXT        CHECK (length(rashi) <= 60),
    family_names   TEXT        CHECK (length(family_names) <= 500),
    puja_date      DATE        NOT NULL,
    phone          TEXT        CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'),
    email          TEXT        CHECK (length(email) <= 254),
    amount_paise   BIGINT      NOT NULL CHECK (amount_paise >= 0),   -- snapshot of the dakshina
    status         TEXT        NOT NULL CHECK (status IN ('AWAITING_PAYMENT', 'CONFIRMED', 'PERFORMED', 'CANCELLED')),
    payment_ref    TEXT        UNIQUE,
    performed_by   BIGINT      REFERENCES app_user(id),
    performed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT puja_booking_code_unique UNIQUE (tenant_id, booking_code),
    CONSTRAINT puja_booking_contact CHECK (phone IS NOT NULL OR email IS NOT NULL),
    -- A paid booking is confirmed only with a verified payment; a free one never has one.
    CONSTRAINT puja_booking_paid CHECK (
        status IN ('AWAITING_PAYMENT', 'CANCELLED')
        OR (amount_paise = 0 AND payment_ref IS NULL)
        OR (amount_paise > 0 AND payment_ref IS NOT NULL)),
    CONSTRAINT puja_booking_performed_shape CHECK ((status = 'PERFORMED') = (performed_at IS NOT NULL))
);
CREATE INDEX idx_puja_booking_date ON puja_booking(tenant_id, puja_date, status);

-- Online payments now settle either a donation (ledger) or a puja booking (seva income).
ALTER TABLE payment_intent ADD COLUMN kind TEXT NOT NULL DEFAULT 'DONATION' CHECK (kind IN ('DONATION', 'PUJA'));
ALTER TABLE payment_intent ADD COLUMN puja_booking_id BIGINT UNIQUE REFERENCES puja_booking(id);
ALTER TABLE payment_intent DROP CONSTRAINT payment_intent_paid_shape;
ALTER TABLE payment_intent ADD CONSTRAINT payment_intent_paid_shape CHECK (
    (status = 'CREATED' AND razorpay_payment_id IS NULL AND donation_id IS NULL) OR
    (status = 'PAID' AND razorpay_payment_id IS NOT NULL AND kind = 'DONATION' AND donation_id IS NOT NULL) OR
    (status = 'PAID' AND razorpay_payment_id IS NOT NULL AND kind = 'PUJA' AND donation_id IS NULL));
ALTER TABLE payment_intent ADD CONSTRAINT payment_intent_kind_shape CHECK (
    (kind = 'DONATION' AND puja_booking_id IS NULL) OR (kind = 'PUJA' AND puja_booking_id IS NOT NULL));

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['puja', 'puja_booking'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I '
            'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint) '
            'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint)',
            t || '_tenant_isolation', t);
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON puja, puja_booking TO sevacenter_app;   -- no DELETE
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
