-- MVP: devotee login with one-time codes by email or SMS (ADR 0018).

-- A code sent to a contact. Neither the contact nor the code is stored: both are HMACs under a
-- server key (SEVACENTER_OTP_KEY), so a database read can't be brute-forced offline or used to
-- learn who logged in.
CREATE TABLE devotee_otp (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL REFERENCES tenant(id),
    channel      TEXT        NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    contact_mac  TEXT        NOT NULL CHECK (length(contact_mac) BETWEEN 20 AND 100),
    code_mac     TEXT        NOT NULL CHECK (length(code_mac) BETWEEN 20 AND 100),
    attempts     INT         NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
    expires_at   TIMESTAMPTZ NOT NULL,
    used_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_devotee_otp_contact ON devotee_otp(tenant_id, contact_mac, created_at);
CREATE INDEX idx_devotee_otp_channel_day ON devotee_otp(tenant_id, channel, created_at);

-- Created only by a successful verification: a contact proven to belong to the person.
CREATE TABLE devotee_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL REFERENCES tenant(id),
    channel       TEXT        NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    contact       TEXT        NOT NULL CHECK (
        (channel = 'EMAIL' AND length(contact) BETWEEN 3 AND 254 AND contact = lower(contact)) OR
        (channel = 'SMS' AND contact ~ '^\+[1-9][0-9]{7,14}$')),
    verified_at   TIMESTAMPTZ NOT NULL,
    last_login_at TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT devotee_account_contact_unique UNIQUE (tenant_id, channel, contact)
);

-- A logged-in devotee. The cookie holds a 256-bit random token; only its SHA-256 is stored.
CREATE TABLE devotee_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenant(id),
    account_id  BIGINT      NOT NULL REFERENCES devotee_account(id),
    token_hash  TEXT        NOT NULL UNIQUE CHECK (length(token_hash) = 64),
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_devotee_session_account ON devotee_session(account_id);

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['devotee_otp', 'devotee_account', 'devotee_session'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I '
            'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint) '
            'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint)',
            t || '_tenant_isolation', t);
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        -- No DELETE: codes and sessions expire or are revoked, leaving an audit trail.
        GRANT SELECT, INSERT, UPDATE ON devotee_otp, devotee_account, devotee_session TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
