-- Audit trail the trust can see (ADR 0020): who did what, when. Append-only: the app role may only
-- read and insert, so nobody (staff, a compromised app, a bug) can edit or erase history.
-- No free text: action is a fixed code, the target is a type + id, and detail is a short value
-- chosen by the code (a role name, an amount), never user input, so no PII lands here.
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenant(id),
    actor_id    BIGINT      REFERENCES app_user(id),               -- null: the public or the system
    action      TEXT        NOT NULL CHECK (action ~ '^[A-Z][A-Z_]{2,39}$'),
    target_type TEXT        CHECK (target_type ~ '^[a-z][a-z_]{1,29}$'),
    target_id   BIGINT,
    detail      TEXT        CHECK (length(detail) <= 80),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_log_tenant_created ON audit_log(tenant_id, created_at DESC, id DESC);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE  ROW LEVEL SECURITY;
CREATE POLICY audit_log_tenant_isolation ON audit_log
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT ON audit_log TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
