-- Earmarked funds (ADR 0022): a per-trust managed list (Annadanam fund, Building fund, ...), so
-- totals per fund don't split on typos the way free text would. Never deleted, only deactivated:
-- ledger entries keep pointing at them.
CREATE TABLE donation_fund (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenant(id),
    name        TEXT        NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
    active      BOOLEAN     NOT NULL DEFAULT true,
    updated_by  BIGINT      NOT NULL REFERENCES app_user(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_donation_fund_name ON donation_fund(tenant_id, lower(name));
-- Target for the composite foreign keys below: a fund can only be referenced from its own trust.
ALTER TABLE donation_fund ADD CONSTRAINT uq_donation_fund_tenant_id UNIQUE (tenant_id, id);

-- A ledger entry's fund (null = the general fund). Set at insert like every ledger column; a
-- reversal carries its donation's fund, so per-fund totals net out.
-- Composite FK: the database itself refuses another trust's fund, whatever the app does.
ALTER TABLE donation ADD COLUMN fund_id BIGINT;
ALTER TABLE donation ADD CONSTRAINT fk_donation_fund
    FOREIGN KEY (tenant_id, fund_id) REFERENCES donation_fund(tenant_id, id);
CREATE INDEX idx_donation_fund ON donation(tenant_id, fund_id);
-- An online donor may earmark their gift; carried to the ledger entry at settlement.
ALTER TABLE payment_intent ADD COLUMN fund_id BIGINT;
ALTER TABLE payment_intent ADD CONSTRAINT fk_payment_intent_fund
    FOREIGN KEY (tenant_id, fund_id) REFERENCES donation_fund(tenant_id, id);

ALTER TABLE donation_fund ENABLE ROW LEVEL SECURITY;
ALTER TABLE donation_fund FORCE  ROW LEVEL SECURITY;
CREATE POLICY donation_fund_tenant_isolation ON donation_fund
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON donation_fund TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
