-- One devotee, several verified contacts (ADR 0025). Each row is a phone or email the devotee
-- proved they own with a one-time code; signing in with any of them opens the same account, and
-- "my seva" shows what was made with any of them.
--
-- No backfill here: under FORCE RLS a migration role without BYPASSRLS would copy nothing, and
-- silently. The app registers an existing account's own contact the next time it signs in.

CREATE TABLE devotee_contact (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL REFERENCES tenant(id),
    account_id  BIGINT      NOT NULL REFERENCES devotee_account(id),
    channel     TEXT        NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    contact     TEXT        NOT NULL CHECK (
        (channel = 'EMAIL' AND length(contact) BETWEEN 3 AND 254 AND contact = lower(contact)) OR
        (channel = 'SMS' AND contact ~ '^\+[1-9][0-9]{7,14}$')),
    verified_at TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT devotee_contact_unique UNIQUE (tenant_id, channel, contact)
);
CREATE INDEX idx_devotee_contact_account ON devotee_contact(account_id);

-- When a devotee links a contact that already had its own account, that account is folded into
-- theirs: its contacts move over and it points here. Kept, not deleted, for the audit trail.
ALTER TABLE devotee_account ADD COLUMN merged_into BIGINT REFERENCES devotee_account(id)
    CHECK (merged_into IS NULL OR merged_into <> id);

-- The devotee's own profile (ADR 0025): what they choose to tell the temple, used to pre-fill a
-- sankalp or a donation. Separate from the staff devotee record, which staff keep with consent.
ALTER TABLE devotee_account
    ADD COLUMN full_name     TEXT CHECK (length(full_name) <= 120),
    ADD COLUMN gotra         TEXT CHECK (length(gotra) <= 60),
    ADD COLUMN nakshatra     TEXT CHECK (length(nakshatra) <= 60),
    ADD COLUMN rashi         TEXT CHECK (length(rashi) <= 60),
    ADD COLUMN date_of_birth DATE CHECK (date_of_birth > DATE '1900-01-01'),
    ADD COLUMN family_names  TEXT CHECK (length(family_names) <= 500),
    ADD COLUMN address_line  TEXT CHECK (length(address_line) <= 200),
    ADD COLUMN city          TEXT CHECK (length(city) <= 80),
    ADD COLUMN state         TEXT CHECK (length(state) <= 80),
    ADD COLUMN pincode       TEXT CHECK (pincode ~ '^[1-9][0-9]{5}$'),
    ADD COLUMN profile_updated_at TIMESTAMPTZ;

ALTER TABLE devotee_contact ENABLE ROW LEVEL SECURITY;
ALTER TABLE devotee_contact FORCE  ROW LEVEL SECURITY;
CREATE POLICY devotee_contact_tenant_isolation ON devotee_contact
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        -- UPDATE only to move a contact when two accounts are merged. No DELETE.
        GRANT SELECT, INSERT, UPDATE ON devotee_contact TO sevacenter_app;
    END IF;
END $$;
