-- M1: multi-tenancy + users, with Postgres Row-Level Security.

-- Tenants (trusts). NO row-level security: this is the tenant registry, read during
-- subdomain routing and written during registration -- both happen OUTSIDE any tenant
-- context. Access is controlled at the application layer.
CREATE TABLE tenant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,                 -- the subdomain label
    name       TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 3-40 chars, lowercase alnum + hyphens, not starting/ending with a hyphen
    CONSTRAINT tenant_slug_format CHECK (slug ~ '^[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])$')
);

-- Application users. Each belongs to exactly one tenant; email is unique per tenant.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenant(id),
    email         TEXT   NOT NULL,
    password_hash TEXT   NOT NULL,
    display_name  TEXT   NOT NULL,
    role          TEXT   NOT NULL CHECK (role IN ('TRUST_ADMIN','LEADER','MEMBER')),
    status        TEXT   NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT app_user_email_per_tenant UNIQUE (tenant_id, email)
);
CREATE INDEX idx_app_user_tenant ON app_user(tenant_id);

-- Row-Level Security on tenant-scoped tables.
-- A session only sees/writes rows for the tenant in the GUC app.tenant_id.
-- current_setting(..., true) returns NULL when unset, so the policy FAILS CLOSED
-- (zero rows) if a request ever forgets to set the tenant.
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_user FORCE  ROW LEVEL SECURITY;   -- defence in depth: applies even to the owner
CREATE POLICY app_user_tenant_isolation ON app_user
    USING      (tenant_id = current_setting('app.tenant_id', true)::bigint)
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);

-- Grant CRUD (not ownership) to the least-privilege runtime role, so RLS always applies
-- to the application. The role is created by the local db-init script / by infra in prod;
-- guard the grants so this migration also runs where the role doesn't exist yet (e.g. tests).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT USAGE ON SCHEMA public TO sevacenter_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON tenant, app_user TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
