-- M1 slice 2b: user lifecycle (pending -> active -> disabled) and one-time setup tokens (ADR 0009).

-- A pending user has no password until they complete setup; an active one must have one.
ALTER TABLE app_user ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE app_user ADD CONSTRAINT app_user_status_valid
    CHECK (status IN ('PENDING', 'ACTIVE', 'DISABLED'));
ALTER TABLE app_user ADD CONSTRAINT app_user_active_has_password
    CHECK (status <> 'ACTIVE' OR password_hash IS NOT NULL);

-- One-time setup links. Only the SHA-256 of the token is stored: the token is a bearer
-- credential, so a database leak must not yield usable links.
CREATE TABLE user_setup_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT      NOT NULL REFERENCES tenant(id),
    user_id    BIGINT      NOT NULL REFERENCES app_user(id),
    token_hash TEXT        NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_setup_token_user ON user_setup_token(user_id);

-- Tenant-scoped, so RLS like app_user (TenantIsolationTest fails the build otherwise): a token
-- issued on tenant A's host can't be redeemed on tenant B's.
ALTER TABLE user_setup_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_setup_token FORCE  ROW LEVEL SECURITY;
CREATE POLICY user_setup_token_tenant_isolation ON user_setup_token
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON user_setup_token TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
