-- M2: devotee records (ADR 0010). Personal data under DPDP: optional fields, consent recorded.

CREATE TABLE devotee (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT      NOT NULL REFERENCES tenant(id),
    full_name           TEXT        NOT NULL CHECK (length(full_name) BETWEEN 1 AND 120),
    phone               TEXT        CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'),       -- E.164
    email               TEXT        CHECK (length(email) <= 254),
    address_line        TEXT        CHECK (length(address_line) <= 200),
    city                TEXT        CHECK (length(city) <= 80),
    state               TEXT        CHECK (length(state) <= 80),
    pincode             TEXT        CHECK (pincode ~ '^[1-9][0-9]{5}$'),
    date_of_birth       DATE        CHECK (date_of_birth > DATE '1900-01-01'),
    consent_source      TEXT        NOT NULL
        CHECK (consent_source IN ('IN_PERSON', 'PHONE', 'ONLINE_FORM', 'WRITTEN')),
    consent_given_at    TIMESTAMPTZ NOT NULL,
    consent_recorded_by BIGINT      NOT NULL REFERENCES app_user(id),
    created_by          BIGINT      NOT NULL REFERENCES app_user(id),
    updated_by          BIGINT      NOT NULL REFERENCES app_user(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Phones aren't unique: families often share one.
CREATE INDEX idx_devotee_tenant_name ON devotee(tenant_id, lower(full_name));

ALTER TABLE devotee ENABLE ROW LEVEL SECURITY;
ALTER TABLE devotee FORCE  ROW LEVEL SECURITY;
CREATE POLICY devotee_tenant_isolation ON devotee
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON devotee TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
