-- M3.1: donation ledger (ADR 0011). Append-only: the app role may only read and insert.

CREATE TABLE donation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id),
    devotee_id      BIGINT      REFERENCES devotee(id),
    donor_name      TEXT        NOT NULL CHECK (length(donor_name) BETWEEN 1 AND 120),
    -- Paise, signed: a donation is positive; a reversal is the negated amount of the donation it
    -- reverses. Max Rs 99,99,99,999.99 per entry.
    amount_paise    BIGINT      NOT NULL CHECK (amount_paise <> 0 AND abs(amount_paise) <= 99999999999),
    mode            TEXT        NOT NULL CHECK (mode IN ('CASH', 'UPI', 'CHEQUE', 'BANK_TRANSFER', 'CARD')),
    reference       TEXT        CHECK (length(reference) <= 64),
    purpose         TEXT        CHECK (length(purpose) <= 120),
    received_on     DATE        NOT NULL CHECK (received_on >= DATE '2000-01-01'),
    reverses_id     BIGINT      UNIQUE REFERENCES donation(id),          -- at most one reversal each
    reversal_reason TEXT        CHECK (length(reversal_reason) BETWEEN 10 AND 300),
    recorded_by     BIGINT      NOT NULL REFERENCES app_user(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT donation_reversal_shape CHECK (
        (reverses_id IS NULL     AND reversal_reason IS NULL     AND amount_paise > 0) OR
        (reverses_id IS NOT NULL AND reversal_reason IS NOT NULL AND amount_paise < 0))
);
CREATE INDEX idx_donation_tenant_received ON donation(tenant_id, received_on);
CREATE INDEX idx_donation_devotee ON donation(devotee_id);

ALTER TABLE donation ENABLE ROW LEVEL SECURITY;
ALTER TABLE donation FORCE  ROW LEVEL SECURITY;
CREATE POLICY donation_tenant_isolation ON donation
    USING      (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);

-- A devotee with donations can't be deleted (the ledger references them): erasure anonymises
-- them instead (ADR 0011). erased_at marks it.
ALTER TABLE devotee ADD COLUMN erased_at TIMESTAMPTZ;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        -- Append-only: no UPDATE, no DELETE. Corrections are reversal rows.
        GRANT SELECT, INSERT ON donation TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
