-- M3.2: 80G receipts (ADR 0012). Donor PAN is encrypted by the application (AES-256-GCM);
-- the database only ever sees ciphertext, the last 4 characters and a keyed blind index.

-- The trust's 80G details, printed on every receipt. One row per tenant.
CREATE TABLE trust_profile (
    tenant_id          BIGINT      PRIMARY KEY REFERENCES tenant(id),
    legal_name         TEXT        NOT NULL CHECK (length(legal_name) BETWEEN 1 AND 200),
    address            TEXT        NOT NULL CHECK (length(address) BETWEEN 1 AND 400),
    pan                TEXT        NOT NULL CHECK (pan ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'),
    registration_80g   TEXT        NOT NULL CHECK (length(registration_80g) BETWEEN 5 AND 60),
    valid_from         DATE        NOT NULL,
    valid_to           DATE        NOT NULL,
    updated_by         BIGINT      NOT NULL REFERENCES app_user(id),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT trust_profile_validity CHECK (valid_to >= valid_from)
);

-- Gapless receipt numbers per tenant per financial year. Taken in the same transaction as the
-- receipt insert (upsert, row-locked), so a rollback returns the number: no gaps, no duplicates.
CREATE TABLE receipt_counter (
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    fy_start  INT    NOT NULL,
    next_seq  INT    NOT NULL CHECK (next_seq >= 1),
    PRIMARY KEY (tenant_id, fy_start)
);

CREATE TABLE receipt (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES tenant(id),
    donation_id      BIGINT      NOT NULL UNIQUE REFERENCES donation(id),   -- one receipt per donation
    fy_start         INT         NOT NULL,
    seq              INT         NOT NULL CHECK (seq >= 1),
    issued_on        DATE        NOT NULL,
    -- Snapshots: an issued receipt never changes, even if the trust or donor record does.
    donor_name       TEXT        NOT NULL,
    donor_address    TEXT        NOT NULL CHECK (length(donor_address) BETWEEN 1 AND 400),
    donor_pan_enc    TEXT        NOT NULL,
    donor_pan_last4  TEXT        NOT NULL CHECK (donor_pan_last4 ~ '^[0-9]{3}[A-Z]$'),
    donor_pan_index  TEXT        NOT NULL,
    amount_paise     BIGINT      NOT NULL CHECK (amount_paise > 0),
    mode             TEXT        NOT NULL,
    received_on      DATE        NOT NULL,
    trust_legal_name TEXT        NOT NULL,
    trust_address    TEXT        NOT NULL,
    trust_pan        TEXT        NOT NULL,
    trust_registration_80g TEXT  NOT NULL,
    issued_by        BIGINT      NOT NULL REFERENCES app_user(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT receipt_number_unique UNIQUE (tenant_id, fy_start, seq)
);
CREATE INDEX idx_receipt_tenant_fy ON receipt(tenant_id, fy_start, seq);
CREATE INDEX idx_receipt_pan_index ON receipt(tenant_id, donor_pan_index);

-- Cancelling a receipt (its donation was reversed) adds a row; the receipt and its number stay.
CREATE TABLE receipt_cancellation (
    receipt_id   BIGINT      PRIMARY KEY REFERENCES receipt(id),
    tenant_id    BIGINT      NOT NULL REFERENCES tenant(id),
    reason       TEXT        NOT NULL CHECK (length(reason) BETWEEN 10 AND 300),
    cancelled_by BIGINT      NOT NULL REFERENCES app_user(id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['trust_profile', 'receipt_counter', 'receipt', 'receipt_cancellation'] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY %I ON %I '
            'USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint) '
            'WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::bigint)',
            t || '_tenant_isolation', t);
    END LOOP;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sevacenter_app') THEN
        GRANT SELECT, INSERT, UPDATE ON trust_profile TO sevacenter_app;
        GRANT SELECT, INSERT, UPDATE ON receipt_counter TO sevacenter_app;
        -- Append-only, like the ledger.
        GRANT SELECT, INSERT ON receipt, receipt_cancellation TO sevacenter_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sevacenter_app;
    END IF;
END $$;
