package app.sevacenter.audit;

/** Everything the trust's audit log records (ADR 0020). Staff actions on people, money and access. */
public enum AuditAction {
    USER_INVITED, USER_ROLE_CHANGED, USER_DEACTIVATED, USER_DELETED, USER_SETUP_LINK_REISSUED,
    USER_RESET_LINK_ISSUED, USER_ACCESS_CHANGED,
    DEVOTEE_CREATED, DEVOTEE_UPDATED, DEVOTEE_ERASED, DEVOTEES_IMPORTED, DEVOTEES_EXPORTED,
    DONATION_RECORDED, DONATION_REVERSED, RECEIPT_ISSUED, TRUST_PROFILE_SAVED, PAYMENT_SETTINGS_SAVED,
    FUND_SAVED, EVENT_STATUS_CHANGED, PUJA_SAVED, PUJA_BOOKING_CANCELLED, SEVAK_REVIEWED, TEMPLE_PAGE_SAVED,
    PUJA_BOOKED_AT_COUNTER, PASS_ISSUED_AT_COUNTER, PRIEST_SAVED, PRIEST_ASSIGNED,
    SEVA_TEAM_SAVED, SEVA_TEAM_DELETED, SEVAK_REGISTERED, SEVAK_ASSIGNED, SEVAK_REMOVED,
    EVENT_DELETED, PUJA_DELETED
}
