#!/usr/bin/env python3
"""Container image policy checks (G6) that Trivy itself doesn't enforce.

  ignores   Every accepted risk in .trivy/accepted.toml needs a scope (one ID, plus paths for a
            misconfiguration), a written reason and an expiry no more than MAX_DAYS out. Valid
            entries are rendered to the YAML ignore file Trivy reads (--write); the TOML stays the
            single source of truth, in the same format as the G3 and G5 accepted risks.
  coverage  The scan must actually have seen the image: an OS was detected and the jar's
            libraries were listed. A scan that silently analysed nothing reports "0
            vulnerabilities" (the G3 lesson), so that is a failure, not a pass.
  gate      Fail on any Critical or High vulnerability that has a fix available. Unfixable ones
            don't block (nobody can act on them) but stay visible in code scanning and are
            re-checked by the daily scan.

Stdlib only (tomllib needs Python 3.11+).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import sys
import tomllib

MAX_DAYS = 90
MIN_REASON = 20
KINDS = {"vulnerability": "vulnerabilities", "misconfiguration": "misconfigurations"}
BLOCKING = {"CRITICAL", "HIGH"}


def ignores(config: str, today: dt.date, write: str | None) -> list[str]:
    path = pathlib.Path(config)
    entries = []
    if path.exists():
        with path.open("rb") as f:
            entries = tomllib.load(f).get("accepted", [])
    errors, valid = [], {k: [] for k in KINDS.values()}
    for e in entries:
        eid = e.get("id") or "<missing id>"
        kind = e.get("kind")
        reason = " ".join((e.get("reason") or "").split())
        until = e.get("ignoreUntil")
        paths = e.get("paths") or []
        problems = []
        if kind not in KINDS:
            problems.append(f"kind must be one of {sorted(KINDS)}")
        if kind == "misconfiguration" and not paths:
            problems.append("a misconfiguration must be scoped to the file(s) it applies to (paths)")
        if len(reason) < MIN_REASON:
            problems.append(f"reason missing or too short (min {MIN_REASON} chars)")
        if until is None:
            problems.append("no ignoreUntil. Every accepted risk must expire")
        else:
            until = until.date() if isinstance(until, dt.datetime) else until
            if until > today + dt.timedelta(days=MAX_DAYS):
                problems.append(f"ignoreUntil {until} is more than {MAX_DAYS} days out")
            elif until < today:
                problems.append(f"expired on {until}. Fix it or re-justify it with a new date")
        if problems:
            errors.extend(f"{eid}: {p}" for p in problems)
            continue  # an invalid entry suppresses nothing
        valid[KINDS[kind]].append((eid, paths, reason, until))
    print(f"{config}: {len(entries)} accepted risk(s) checked, {sum(map(len, valid.values()))} valid")
    if write:
        pathlib.Path(write).write_text(render(valid), encoding="utf-8")
    return errors


def render(valid: dict[str, list]) -> str:
    """Trivy's ignore-file YAML. json.dumps gives double-quoted strings, which are valid YAML."""
    out = ["# Generated by tools/security/image_policy.py from .trivy/accepted.toml. Don't edit."]
    for section, items in valid.items():
        if not items:
            continue
        out.append(f"{section}:")
        for eid, paths, reason, until in items:
            out.append(f"  - id: {json.dumps(eid)}")
            if paths:
                out.append("    paths:")
                out.extend(f"      - {json.dumps(p)}" for p in paths)
            out.append(f"    statement: {json.dumps(reason)}")
            out.append(f"    expired_at: {until.isoformat()}")
    return "\n".join(out) + "\n"


def coverage(trivy_json: str) -> list[str]:
    report = json.loads(pathlib.Path(trivy_json).read_text(encoding="utf-8"))
    errors = []
    os_info = (report.get("Metadata") or {}).get("OS") or {}
    if not os_info.get("Family"):
        errors.append("no operating system detected in the image: the OS packages were not scanned")
    results = report.get("Results") or []
    os_pkgs = sum(len(r.get("Packages") or []) for r in results if r.get("Class") == "os-pkgs")
    jar_pkgs = sum(len(r.get("Packages") or []) for r in results if r.get("Type") == "jar")
    if os_pkgs == 0:
        errors.append("0 OS packages listed (scan with --list-all-pkgs, and check the image)")
    if jar_pkgs == 0:
        errors.append("0 Java libraries listed: the application jar was not analysed")
    print(f"coverage: {os_info.get('Family')} {os_info.get('Name')}, {os_pkgs} OS packages, {jar_pkgs} Java libraries")
    return errors


def gate(trivy_json: str) -> list[str]:
    report = json.loads(pathlib.Path(trivy_json).read_text(encoding="utf-8"))
    errors, unfixed = [], 0
    for r in report.get("Results") or []:
        for v in r.get("Vulnerabilities") or []:
            if v.get("Severity") not in BLOCKING:
                continue
            if not v.get("FixedVersion"):
                unfixed += 1
                continue
            errors.append(f"[{v['Severity'].lower()}] {v['VulnerabilityID']} in {v['PkgName']} "
                          f"{v.get('InstalledVersion')} ({r.get('Target')}): fixed in {v['FixedVersion']}. "
                          "Rebuild on a patched base image or bump the library, or accept it in "
                          ".trivy/accepted.toml with a reason + expiry")
    print(f"image gate: {len(errors)} fixable critical/high, {unfixed} critical/high with no fix yet (reported, not blocking)")
    return errors


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    i = sub.add_parser("ignores", help="accepted risks are scoped, reasoned and expiring")
    i.add_argument("config", nargs="?", default=".trivy/accepted.toml")
    i.add_argument("--write", help="render valid entries to this Trivy ignore file (YAML)")
    c = sub.add_parser("coverage", help="the scan really analysed the OS and the jar")
    c.add_argument("trivy_json", help="trivy image --format json --list-all-pkgs output")
    g = sub.add_parser("gate", help="fail on fixable critical/high vulnerabilities")
    g.add_argument("trivy_json", help="trivy image --format json output (ignore file applied)")
    args = p.parse_args()

    if args.cmd == "ignores":
        errors = ignores(args.config, dt.date.today(), args.write)
    elif args.cmd == "coverage":
        errors = coverage(args.trivy_json)
    else:
        errors = gate(args.trivy_json)
    for e in errors:
        print(f"::error::{e}")  # GitHub Actions annotation; plain text locally
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
