/** Every action the audit log records, for the filter. Kept identical to AuditAction.java by a test. */
export const AUDIT_ACTIONS = [
  "USER_INVITED", "USER_ROLE_CHANGED", "USER_DEACTIVATED", "USER_DELETED", "USER_SETUP_LINK_REISSUED",
  "USER_RESET_LINK_ISSUED", "DEVOTEE_CREATED", "DEVOTEE_UPDATED", "DEVOTEE_ERASED", "DEVOTEES_IMPORTED",
  "DEVOTEES_EXPORTED", "DONATION_RECORDED", "DONATION_REVERSED", "RECEIPT_ISSUED", "TRUST_PROFILE_SAVED",
  "PAYMENT_SETTINGS_SAVED", "EVENT_STATUS_CHANGED", "PUJA_SAVED", "PUJA_BOOKING_CANCELLED", "SEVAK_REVIEWED",
  "TEMPLE_PAGE_SAVED", "USER_ACCESS_CHANGED", "FUND_SAVED", "PUJA_BOOKED_AT_COUNTER", "PASS_ISSUED_AT_COUNTER",
  "PRIEST_SAVED", "PRIEST_ASSIGNED", "SEVA_TEAM_SAVED", "SEVA_TEAM_DELETED", "SEVAK_REGISTERED", "SEVAK_ASSIGNED",
  "SEVAK_REMOVED", "EVENT_DELETED", "PUJA_DELETED",
] as const;
